name: CI Github Pages
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - name: Checkout  ️ 
        uses: actions/checkout@v3

      - name: Deploy   
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: site 
          folder: ./site/docs/..vitepress/dist
